modLoader = "javafml"
loaderVersion = "${forgeLoaderVersion}"
license = "All Rights Reserved"

[[mods]]
modId = "tensuraiaf"
version = "${modVersion}"
displayName = "Tensura Compat: Ice and Fire"

authors = "MinhEragon"
description = '''
A Compat mod between Tensura:Reincarnated & Ice and Fire.
'''

[[dependencies.tensuraiaf]]
    modId = "forge"
    mandatory = true
    versionRange = "${forgeLoaderVersion}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tensuraiaf]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraftVersionCheck}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tensuraiaf]]
    modId="iceandfire"
    mandatory=true
    versionRange="${iafVersionCheck}"
    ordering="NONE"
    side="BOTH"